---
- name: Check JDK Zulu version
  hosts: actone
  gather_facts: no
  become: yes
  tasks:
    - name: Check JAVA version
      ansible.builtin.shell: source /etc/profile.d/java.sh && java -version
      register: java_version
      changed_when: false

    - name: Show Java Version
      debug:
        var: java_version.stderr_lines
