---
- name: Install IFM 11
  hosts: actone
  gather_facts: no
  become: yes
  tasks:
    - name: Ping server
      ansible.builtin.ping:
    
    - name: Copy IFM installer file to server
      ansible.builtin.copy:
        remote_src: false
        src: "{{ playbook_dir }}/../installer-ifm"
        dest: /home/actimize/Downloads
        mode: '0644'

    - name: Unzip installer
      ansible.builtin.unarchive:
        src: "/home/actimize/Downloads/installer-ifm/{{ item }}"
        dest: /home/actimize/Downloads/installer-ifm
        remote_src: yes
        mode: 0777
      loop:
        - IFM-11.0.0-2024-06.zip

    - name: Copy configured conf file to installer
      ansible.builtin.copy:
        remote_src: true
        src: /home/actimize/Downloads/installer-actone/conf/Installer/conf
        dest: /home/actimize/Downloads/installer-actone/Installer
        mode: '0777'
#    - name: Config IFM conf file

#    - name: Run IFM installer

#    - name: Restart AIS-IFM server
    
#    - name: Test AIS-IFM connector