---
- name: Install and Configure PostgreSQL 16
  hosts: actone
  become: yes
  gather_facts: no

  tasks:
    - name: Import PostgreSQL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL

    - name: Install PostgreSQL YUM Repository
      ansible.builtin.dnf:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

#    - name: Disable built-in PostgreSQL module
#      ansible.builtin.shell: dnf -qy module disable postgresql

    - name: Install PostgreSQL 16 packages
      ansible.builtin.dnf:
        name:
          - postgresql16
          - postgresql16-server
        state: present

    - name: Initialize PostgreSQL Database
      ansible.builtin.shell: /usr/pgsql-16/bin/postgresql-16-setup initdb
      args:
        creates: /var/lib/pgsql/16/data/PG_VERSION

    - name: Enable and start PostgreSQL 16 service
      ansible.builtin.service:
        name: postgresql-16
        state: started
        enabled: true

    - name: Check PostgreSQL version
      ansible.builtin.command: /usr/pgsql-16/bin/psql --version
      register: postgres_version
      changed_when: false

    - name: Show PostgreSQL version
      ansible.builtin.debug:
        var: postgres_version.stdout

    - name: Install psycopg2 library from RPM
      ansible.builtin.dnf:
        name: python3-psycopg2
        state: present
        
    - name: Create testuser in PostgreSQL
      become_user: postgres
      ansible.builtin.postgresql_user:
        name: testuser
        password: password
        role_attr_flags: SUPERUSER
