---
- name: Check JDK Zulu version
  hosts: debian
  gather_facts: no
  become: no
  tasks:
    - name: Ping server
      ansible.builtin.ping:

    - name: Check JAVA version
      ansible.builtin.command: java -version
      register: java_version
      changed_when: false
