---
- name: Install JDK Zulu
  hosts: debian
  gather_facts: no
  become: yes
  tasks:
    - name: Ping server
      ansible.builtin.ping:

    - name: Install Python if missing (via raw)
      ansible.builtin.raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          sudo apt update && sudo apt install -y python3
        fi

    - name: Download Zulu OpenJDK 11
      ansible.builtin.get_url:
        url: https://cdn.azul.com/zulu/bin/zulu11.78.15-ca-jdk11.0.26-linux_aarch64.tar.gz
        dest: /tmp/zulu11.tar.gz
        mode: '0644'
        force: no

    - name: Ensure /opt/zulu directory exists
      ansible.builtin.file:
        path: /opt/zulu
        state: directory
        mode: '0755'
        
    - name: Extract JDK to /opt/zulu
      ansible.builtin.unarchive:
        src: /tmp/zulu11.tar.gz
        dest: /opt/zulu
        remote_src: yes

    - name: Create JAVA_HOME profile script
      ansible.builtin.copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/opt/zulu/zulu11.78.15-ca-jdk11.0.26-linux_aarch64
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0755'

    - name: Symlink java to /usr/bin
      ansible.builtin.file:
        src: /opt/zulu/zulu11.78.15-ca-jdk11.0.26-linux_aarch64/bin/java
        dest: /usr/bin/java
        state: link

    - name: Check JAVA version
      ansible.builtin.command: java -version
      register: java_version
      changed_when: false

    - name: Show Java Version
      ansible.builtin.debug:
        var: java_version.stderr_lines
